name: classroom_scheduler_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.4.0
  cloud_firestore: ^1.0.4
  connectivity: ^3.0.2
  cupertino_icons: ^1.0.0
  device_info: ^2.0.0
  equatable: ^2.0.2
  feature_discovery: ^0.14.0
  # file_picker: ^3.0.2+2
  firebase_auth: ^1.0.3
  firebase_core: ^1.0.3
  firebase_dynamic_links: ^0.8.0
  firebase_messaging: ^9.1.1
  firebase_storage: ^8.0.5
  flutter_animated_dialog: ^2.0.0
  flutter_icons: ^1.1.0
  flutter_local_notifications: ^5.0.0+1
  flutter_offline: ^2.0.0
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^0.19.3
  giffy_dialog: ^1.8.0
  google_sign_in: ^5.0.0
  http: ^0.13.1
  image_picker: ^0.7.4
  intl: ^0.17.0
  logger: ^1.0.0
  mime: ^1.0.0
  mime_type: ^1.0.0
  open_file: ^3.2.1
  path: ^1.8.0
  path_provider_ex: ^1.0.1
  permission_handler: ^8.0.0+2
  photo_view: ^0.11.1
  provider: null
  rounded_loading_button: ^1.0.18
  share: ^2.0.1
  shared_preferences: ^2.0.5
  system_settings: ^2.0.0
  url_launcher: ^6.0.3
  weekday_selector: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.8.0

flutter_icons:

  image_path: "image/icons8-clock.png"
  android: true
  ios: true

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - image/

  fonts:
    - family: AkayaTelivigala
      fonts:
        - asset: fonts\AkayaTelivigala-Regular.ttf

    - family: Damion
      fonts:
        - asset: fonts\Damion-Regular.ttf
    - family: Redressed
      fonts:
        - asset: fonts\Redressed-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
